spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 
  data:
    redis:
      host:
      port: 

mybatis:
  configuration:
    map-underscore-to-camel-case: true
